# Dynamic configuration
http:
  middlewares:
    redirect-to-www:
      redirectregex:
        regex: "^(http|https)://(?:www\\.)?(.+)"
        replacement: "${1}://www.${2}"
        permanent: true
    redirect-to-non-www:
      redirectregex:
        regex: "^(http|https)://(?:www\\.)?(.+)"
        replacement: "${1}://${2}"
        permanent: true
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    user-auth:
      basicAuth:
        users:
          # Generate in https://www.web2generators.com/apache-tools/htpasswd-generator
          - "admin:$apr1$xqfcytm1$5uMBJ6M7zyw5ARi3Gy5SD0" # admin:admin

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
