version: "3.8"

services:
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}-traefik
    image: traefik:${TRAEFIK_VERSION:-latest}
    restart: ${TRAEFIK_RESTART:-no}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - ${TRAEFIK_PORT:-80}:80
      - ${TRAEFIK_SECURE_PORT:-443}:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/traefik.yml:/traefik.yml:ro
      - ./traefik-data/acme.json:/acme.json
      - ./traefik-data/configurations:/configurations
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-traefik.entrypoints=${TRAEFIK_ENTRYPOINT:-web}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-traefik.rule=Host(${TRAEFIK_DOMAIN:-`traefik.localhost`})
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-traefik.service=api@internal
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-traefik.middlewares=user-auth@file

  portainer:
    container_name: ${COMPOSE_PROJECT_NAME}-portainer
    profiles: ["all", "portainer"]
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    restart: ${PORTAINER_RESTART:-no}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-portainer.entrypoints=${PORTAINER_ENTRYPOINT:-web}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-portainer.rule=Host(${PORTAINER_DOMAIN:-`portainer.localhost`})
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-portainer.service=portainer
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-portainer.loadbalancer.server.port=9000
    depends_on:
      - traefik

  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    profiles: ["all", "mariadb", "mysql", "phpmyadmin", "pma"]
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: ${MARIADB_RESTART:-no}
    volumes:
      - ./mariadb-data/data:/var/lib/mysql
      - ./mariadb-data/init:/docker-entrypoint-initdb.d
    ports:
      - ${MARIADB_PORT:-3306}:3306
    environment:
      - TZ=${MARIADB_TZ}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-root}
    networks:
      - proxy

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    profiles: ["all", "phpmyadmin", "pma"]
    image: phpmyadmin:${PMA_VERSION:-latest}
    restart: ${PMA_RESTART:-no}
    environment:
      - PMA_ARBITRARY=1
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin.entrypoints=${PMA_ENTRYPOINT:-web}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin.rule=Host(${PMA_DOMAIN:-`pma.localhost`})
    networks:
      - proxy
    depends_on:
      - mariadb
      - traefik

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    profiles: ["all", "postgres", "pgadmin"]
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: ${POSTGRES_RESTART:-no}
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
      - ./postgres-data/init:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    networks:
      - proxy

  pgadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-pgadmin
    profiles: ["all", "pgadmin"]
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    restart: ${PGADMIN_RESTART:-no}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-pgadmin.entrypoints=${PGADMIN_ENTRYPOINT:-web}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-pgadmin.rule=Host(${PGADMIN_DOMAIN:-`pgadmin.localhost`})
    networks:
      - proxy
    depends_on:
      - postgres
      - traefik

  mongo:
    container_name: ${COMPOSE_PROJECT_NAME}-mongo
    profiles: ["all", "mongo", "mongodb", "mongo-express"]
    image: mongo:${MONGO_VERSION:-latest}
    restart: ${MONGO_RESTART:-no}
    volumes:
      - ./mongo-data/data:/data/db
      - ./mongo-data/configdb:/data/configdb
      - ./mongo-data/init:/docker-entrypoint-initdb.d
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-example}
    networks:
      - proxy

  mongo-express:
    container_name: ${COMPOSE_PROJECT_NAME}-mongo-express
    profiles: ["all", "mongo-express"]
    image: mongo-express:${MONGO_EXPRESS_VERSION:-latest}
    restart: ${MONGO_EXPRESS_RESTART:-no}
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_ADMINUSERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_ADMINPASSWORD:-example}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-example}@mongo:27017/
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-mongo-express.entrypoints=${MONGO_EXPRESS_ENTRYPOINT:-web}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-mongo-express.rule=Host(${MONGO_EXPRESS_DOMAIN:-`mongo.localhost`})
    networks:
      - proxy
    depends_on:
      - mongo
      - traefik

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    profiles: ["all", "redis"]
    restart: ${REDIS_RESTART:-no}
    image: redis:${REDIS_VERSION:-latest}
    volumes:
      - ./redis-data:/data
    command: --requirepass ${REDIS_PASSWORD:-redis}
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - proxy

networks:
  proxy:
    external: true
